### ISSUE TITLE
Faltando Tracking Code do Google Analytics em index.html

### ISSUE THREAD

**Issue by soapdog** [keppelen/chatty#1]
Fala Gente,

O tracking code do Google Analytics está em branco no index.html

**Comment by keppelen** [comment]
@soapdog 

Cria para gente? Esta no seu dominio, vou lhe mandar também um novo build ok?

**Comment by MarioRinaldi** [comment]
Seria o caso de criar um analytics "mozilla brasil" ? site, apps, etc?

**Comment by keppelen** [comment]
@MarioRinaldi Concordo 100%, dai não fica restringido a 1 pessoa.

**Comment by bernarddeluna** [comment]
perfeito

**Comment by keppelen** [comment]
Alguém pode criar? @cstipkovic @soapdog @andrenatal @MarioRinaldi
