### ISSUE TITLE
Travar botão salvar quando não estão selecionados os locais origem e destino

### ISSUE THREAD

**Issue by MarioRinaldi** [keppelen/chatty#6]
Esperado:
- Ao acessar a tela de mudança dos locais, permitir prosseguir apenas quando a origem e o destino forem selecionados.

O que ocorre atuamente:
- se deixar ambos sem seleção, ao prosseguir causa tilt na tela de lista + form;

**Comment by cstipkovic** [comment]
Duvida.
Qual o melhor comportamento, esconder o botao ou deixar desabilitado, com uma cor diferente?!

**Comment by s1xtec** [comment]
Acho o 'efeito' de desabilitado mais coerente. Outra cor no estilo 'fantasminha' funciona meio que padrão em todos os lugares.
