### ISSUE TITLE
investigar loading do app

### ISSUE THREAD

**Issue by bernarddeluna** [keppelen/chatty#7]
No android ele já vem com um loading proprio. Investigar se há a necessidade da tela de loading que criamos ou nao

**Comment by s1xtec** [comment]
Talvez ler o 'user-agent' para reconhecer o Android e mudar a entrada p ele então... Pq acho que ela deve ser mantida, mas tem que aumentar mais o tempo de exibição. Tá muito rápido, tão rápido que as vezes não carrega o logo, fica aquele quadrado de que ali existe uma imagem, mas 'não possível carregar' e já apaga.
