### ISSUE TITLE
Criar uma maneira *fácil* de sugerir expressões, traduções ou revisões.

### ISSUE THREAD

**Issue by MarioRinaldi** [keppelen/chatty#8]
Bolar uma forma de captar sugestões e contribuições de uma forma fácil e rápida, seja dentro do app ou num website, além da forma padrão de clonar o projeto, alterar e submeter "pull request".

**Comment by s1xtec** [comment]
Uma forma é criando um link "mailto:chatty@domínio.com.br?subject=Add expression" onde o user pudesse escrever aí. Todos os users podem se beneficiar disso e nós faríamos desse e-mail um alias, que cairá para todos e daí, fazermos a adição 'manual' desse conteúdo (Essa é a forma difícil). 

Outra forma é criarmos dentro do domínio do André (ou de qualquer outro, quem sabe um próprio para o nosso app, não vejo dificuldades nisso) um BD mysql por exemplo e uma tela com um form para o user adicionar isso. Depois, criamos um 'painel de controle' e aprovamos as expressões (Essa é a forma que eu julgo fácil). Daí na tela inicial o Chatty sempre chamaria o BD e exibiria os registros.
